gantt
    dateFormat YYYY-Q
    axisFormat  %Y-%m
    title Analysis Systems NSF Milestones

    section Analysis Systems
    Organize topical meetings                                   :done,   2019-2, 2019-3
    List public repos on website                                :done,   2019-3, 2020-1
    Collect and curate existing example analysis use cases      :done,   2019-3, 2020-1
    Survey of AS efforts in the field for topical workshop      :done,   2019-3, 2020-1
    Blueprint workshop for evaluating AS                        :active, 2019-3, 2020-1
    Develop initial specifications for user-facing interface    :active, 2019-3, 2020-1
    Prototype awkward-array analyses in SciPy ecosystem         :done,   2019-3, 2020-1
    # Future work
    Initial roadmap for ecosystem coherency                     :crit,   2019-4, 2020-3
    Initial interface of AS-IDDS query system                   :        2019-4, 2020-2
    Translate analysis examples into new specifications         :        2019-4, 2020-2
    Initial roadmap for high-level cyberinfrastructure          :crit,   2019-4, 2020-3
    Benchmarking and assessment of existing AS                  :crit,   2020-1, 2020-3
    Prototype query-based & cache-aware dispatch                :        2020-2, 2020-4
    Analysis description database schema w/ archival integration:        2020-1, 2021-1
    Accelerator implementations of statistical components       :crit,   2020-1, 2020-3
    Move prototypes of AS components to SSL                     :        2020-3, 2021-1
    Benchmarking and assessment of prototype components         :        2020-3, 2021-1
