gantt
    dateFormat YYYY-Q
    axisFormat  %Y-%m

    section Gantt Colors
    Task Completed          :done,   2019-2, 2019-3
    Task Currently WIP      :active, 2019-3, 2019-4
    Future Task             :        2019-4, 2020-1
    Nota Bene / Critical    :crit,   2019-3, 2020-1
