gantt
    dateFormat YYYY-Q
    axisFormat  %Y-%m
    title pyhf 2019 into 2020 Roadmap

    section Documentation and Deployment
    Add docstrings to all functions and classes :active, 2019-3, 2019-4
    Greatly revise and expand examples          :        2019-3, 2020-1
    Move to scikit-hep GitHub org               :active, 2019-3, 2019-4
    Develop a release schedule/criteria         :        2019-3, 2019-4
    Automate deployment with Azure pipelines    :        2019-4, 2020-1
    Finalize logo and add it to website         :        2019-3, 2020-1
    Write submission to JOSS and pyOpenSci      :        2019-4, 2020-2

    section Revision and Maintenance
    Add tests using HEPData published likelihoods           :active, 2019-3, 2019-4
    Add CI with GitHub Actions                              :done,   2019-3, 2019-4
    Rewrite pytest fixtures to use modern pytest            :        2019-3, 2020-1
    Factorize out the statistical fitting portion           :active, 2019-3, 2020-1
    Scrutinize edge cases/squash bugs                       :active, 2019-3, 2020-2
    Reproduce sbottom serialization PUB note across backends:        2019-4, 2020-2

    section Development
    Add batch support                           :done,   2019-3, 2019-4
    Add ParamViewer support                     :done,   2019-3, 2019-4
    Implement pdf as subclass of distributions  :active, 2019-3, 2019-4
    Finalize toy sampling                       :active, 2019-3, 2019-4
    Make general modeling choices               :        2019-4, 2020-2
    Add "discovery" test stats public API       :        2019-4, 2020-2
    Add better Model creation                   :        2019-4, 2020-2
    Add background model support                :        2019-4, 2020-2
    Develop interface for the optimizers        :        2019-4, 2020-2
    Migrate to TensorFlow 2.0                   :        2019-4, 2020-1
    Finalize public API                         :        2020-1, 2020-2
    Integrate pyfitcore API                     :        2020-1, 2020-2
    Drop Python 2.7 support                     :active, py2EOL, 2019-4, 2020-1

    section Research
    pyfitcore integrations                  :        before py2EOL, 2020-1
    Hardware acceleration scaling studies   :        2019-4,        2020-2
    Speedup through Numba                   :active, 2019-3,        2020-1
    Add Dask backend:                       :        2020-1,        2020-2
    Prototype use of pyhf as AS end fit too:        2019-4,        2020-2

    section Analysis Systems
    Organize topical meetings                                   :done,   2019-2, 2019-3
    List public repos on website                                :done,   2019-3, 2020-1
    Collect and curate existing example analysis use cases      :done,   2019-3, 2020-1
    Survey of AS efforts in the field for topical workshop      :done,   2019-3, 2020-1
    Blueprint workshop for evaluating AS                        :active, 2019-3, 2020-1
    Develop initial specifications for user-facing interface    :active, 2019-3, 2020-1
    Prototype awkward-array analyses in SciPy ecosystem         :done,   2019-3, 2020-1
    # Future work
    Initial roadmap for ecosystem coherency                    :crit,   2019-4, 2020-3
    Initial interface of AS-IDDS query system                   :        2019-4, 2020-2
    Translate analysis examples into new specifications         :        2019-4, 2020-2
    Initial roadmap for high-level cyberinfrastructure          :crit,   2019-4, 2020-3
    Benchmarking and assessment of existing AS                  :crit,   2020-1, 2020-3
#    Prototype query-based & cache-aware dispatch                :        2020-2, 2020-4
#    Analysis description database schema w/ archival integration:        2020-1, 2021-1
    Accelerator implementations of statistical components    :crit,    2020-1, 2020-3
#    Move prototypes of AS components to SSL                     :        2020-3, 2021-1
#    Benchmarking and assessment of prototype components         :        2020-3, 2021-1
