gantt
    dateFormat YYYY-Q
    axisFormat  %Y-%m

    section Docs/Deploy
    Documentation, Examples     :active, 2019-3, 2020-1
    JOSS, pyOpenSci, pyhf paper :        2019-4, 2020-2

    section Maintenance
    Testing with published likelihoods      :active, 2019-3, 2020-2
    Improvement of testing infrastructure   :        2019-3, 2020-1

    section Development
    Add batch support           :done,   2019-3, 2019-4
    Add toys                    :active, 2019-3, 2019-4
    Finalize public API         :        2019-4, 2020-2
    Integrate pyfitcore API :        2019-4, 2020-2

    section Research
    pyfitcore integrations              :        before py2EOL, 2020-1
    Speedup, Acceleration, Scaling studies  :        2019-4,        2020-2
    Prototype use of pyhf as AS end fit tool:        2019-4,        2020-2

    section Analysis Systems
    Initial roadmap for ecosystem coherency                 :crit,   2019-4, 2020-3
    Initial roadmap for high-level cyberinfrastructure      :crit,   2019-4, 2020-3
    Benchmarking and assessment of existing AS              :crit,   2020-1, 2020-3
    Accelerator implementations of statistical components   :crit,    2020-1, 2020-3
