gantt
    dateFormat YYYY-Q
    axisFormat  %Y-%m
    title Revision and Maintenance

    section Maintenance
    Add tests using HEPData published likelihoods           :active, 2019-3, 2019-4
    Add CI with GitHub Actions                              :done,   2019-3, 2019-4
    Rewrite pytest fixtures to use modern pytest            :        2019-3, 2020-1
    Factorize out the statistical fitting portion           :active, 2019-3, 2020-1
    Scrutinize edge cases/squash bugs                       :active, 2019-3, 2020-2
    Reproduce sbottom serialization PUB note across backends:        2019-4, 2020-2
