gantt
    dateFormat YYYY-Q
    axisFormat  %Y-%m
    title Research

    section Research
    Statisfactory integrations              :        before py2EOL, 2020-1
    Hardware acceleration scaling studies   :        2019-4,        2020-2
    Speedup through Numba                   :active, 2019-3,        2020-1
    Add Dask backend:                       :        2020-1,        2020-2
    Prototype use of pyhf as AS end fit tool:        2019-4,        2020-2
