gantt
    dateFormat YYYY-Q
    axisFormat  %Y-%m
    title Documentation and Deployment

    section Docs/Deploy
    Add docstrings to all functions and classes :active, 2019-3, 2019-4
    Greatly revise and expand examples          :        2019-3, 2020-1
    Move to scikit-hep GitHub org               :active, 2019-3, 2019-4
    Develop a release schedule/criteria         :        2019-3, 2019-4
    Automate deployment with Azure pipelines    :        2019-4, 2020-1
    Finalize logo and add it to website         :        2019-3, 2020-1
    Write submission to JOSS and pyOpenSci      :        2019-4, 2020-2
