gantt
    dateFormat YYYY-Q
    axisFormat  %Y-%m
    title Development

    section Development
    Add batch support                           :done,   2019-3, 2019-4
    Add ParamViewer support                     :done,   2019-3, 2019-4
    Implement pdf as subclass of distributions  :active, 2019-3, 2019-4
    Finalize toy sampling                       :active, 2019-3, 2019-4
    Make general modeling choices               :        2019-4, 2020-2
    Add "discovery" test stats public API       :        2019-4, 2020-2
    Add better Model creation                   :        2019-4, 2020-2
    Add background model support                :        2019-4, 2020-2
    Develop interface for the optimizers        :        2019-4, 2020-2
    Migrate to TensorFlow 2.0                   :        2019-4, 2020-1
    Finalize public API                         :        2020-1, 2020-2
    Integrate pyfitcore API                 :        2020-1, 2020-2
    Drop Python 2.7 support                     :active, py2EOL, 2019-4, 2020-1
